// 500 palabras de inglés organizadas en 10 semanas (50 por semana)
// Niveles A2 -> B2, las más útiles para business + day-to-day
const PALABRAS = {
  1: [
    {en: "achieve", es: "lograr", ej: "We achieved our sales goal."},
    {en: "afford", es: "permitirse", ej: "I can't afford a new car."},
    {en: "allow", es: "permitir", ej: "We allow remote work."},
    {en: "amount", es: "cantidad", ej: "A large amount of money."},
    {en: "approach", es: "enfoque / acercarse", ej: "We need a new approach."},
    {en: "available", es: "disponible", ej: "Are you available tomorrow?"},
    {en: "avoid", es: "evitar", ej: "Avoid that mistake."},
    {en: "behavior", es: "comportamiento", ej: "His behavior was strange."},
    {en: "benefit", es: "beneficio", ej: "The benefits are clear."},
    {en: "borrow", es: "pedir prestado", ej: "Can I borrow your pen?"},
    {en: "budget", es: "presupuesto", ej: "We're over budget."},
    {en: "challenge", es: "desafío", ej: "It's a big challenge."},
    {en: "claim", es: "reclamar / afirmar", ej: "She claims it's true."},
    {en: "concern", es: "preocupación", ej: "I share your concern."},
    {en: "confirm", es: "confirmar", ej: "Please confirm the meeting."},
    {en: "consider", es: "considerar", ej: "Consider all options."},
    {en: "contain", es: "contener", ej: "The box contains books."},
    {en: "decrease", es: "disminuir", ej: "Sales decreased last month."},
    {en: "deliver", es: "entregar", ej: "We deliver on time."},
    {en: "deserve", es: "merecer", ej: "You deserve a break."},
    {en: "discover", es: "descubrir", ej: "We discovered a bug."},
    {en: "due", es: "debido / vencido", ej: "The payment is due Friday."},
    {en: "enough", es: "suficiente", ej: "That's enough for today."},
    {en: "expect", es: "esperar (esperarse)", ej: "I expect good results."},
    {en: "fail", es: "fallar", ej: "Don't fail the test."},
    {en: "fee", es: "tarifa", ej: "There's a service fee."},
    {en: "figure out", es: "averiguar", ej: "Let me figure it out."},
    {en: "goal", es: "objetivo", ej: "Our goal is growth."},
    {en: "growth", es: "crecimiento", ej: "Steady growth this year."},
    {en: "hire", es: "contratar", ej: "We hired three people."},
    {en: "improve", es: "mejorar", ej: "We must improve quality."},
    {en: "income", es: "ingresos", ej: "Annual income increased."},
    {en: "increase", es: "aumentar", ej: "Prices will increase."},
    {en: "issue", es: "problema / asunto", ej: "We have an issue."},
    {en: "lack", es: "falta", ej: "Lack of resources."},
    {en: "manage", es: "gestionar", ej: "She manages the team."},
    {en: "owe", es: "deber (dinero)", ej: "I owe you 50 euros."},
    {en: "own", es: "poseer / propio", ej: "I own this car."},
    {en: "perform", es: "realizar / actuar", ej: "We performed well."},
    {en: "provide", es: "proporcionar", ej: "We provide support."},
    {en: "raise", es: "subir / aumentar", ej: "Raise your hand."},
    {en: "rather", es: "más bien / preferir", ej: "I'd rather stay home."},
    {en: "reach", es: "alcanzar", ej: "We reached the target."},
    {en: "reduce", es: "reducir", ej: "Reduce costs by 10%."},
    {en: "require", es: "requerir", ej: "This requires effort."},
    {en: "save", es: "ahorrar / guardar", ej: "Save your work."},
    {en: "spend", es: "gastar", ej: "Don't spend too much."},
    {en: "support", es: "apoyar", ej: "I support this idea."},
    {en: "task", es: "tarea", ej: "Complete this task today."},
    {en: "waste", es: "desperdiciar", ej: "Don't waste time."}
  ],
  2: [
    {en: "ability", es: "habilidad", ej: "She has the ability to lead."},
    {en: "accept", es: "aceptar", ej: "I accept your offer."},
    {en: "access", es: "acceso", ej: "Do you have access?"},
    {en: "according to", es: "según", ej: "According to the report."},
    {en: "accurate", es: "preciso", ej: "Accurate data is key."},
    {en: "actually", es: "en realidad", ej: "Actually, it's true."},
    {en: "add", es: "añadir", ej: "Add salt to the dish."},
    {en: "advice", es: "consejo", ej: "Good advice, thanks."},
    {en: "agree", es: "estar de acuerdo", ej: "I agree with you."},
    {en: "ahead", es: "adelante / por delante", ej: "Go ahead."},
    {en: "aim", es: "objetivo / apuntar", ej: "Our aim is clear."},
    {en: "answer", es: "respuesta", ej: "What's your answer?"},
    {en: "anyway", es: "de todos modos", ej: "Thanks anyway."},
    {en: "appear", es: "aparecer / parecer", ej: "She appears tired."},
    {en: "apply", es: "aplicar / postularse", ej: "Apply for the job."},
    {en: "argue", es: "discutir", ej: "Don't argue with him."},
    {en: "arrive", es: "llegar", ej: "We arrived late."},
    {en: "ask", es: "preguntar / pedir", ej: "Ask a question."},
    {en: "asleep", es: "dormido", ej: "He fell asleep."},
    {en: "attempt", es: "intentar", ej: "A second attempt."},
    {en: "attend", es: "asistir", ej: "Attend the meeting."},
    {en: "audience", es: "público", ej: "Large audience tonight."},
    {en: "average", es: "promedio", ej: "Above average performance."},
    {en: "awake", es: "despierto", ej: "Are you awake yet?"},
    {en: "award", es: "premio", ej: "She won an award."},
    {en: "aware", es: "consciente", ej: "Be aware of the risks."},
    {en: "balance", es: "equilibrio / saldo", ej: "Work-life balance."},
    {en: "base", es: "base", ej: "Our base is here."},
    {en: "become", es: "convertirse", ej: "He became CEO."},
    {en: "begin", es: "comenzar", ej: "Let's begin."},
    {en: "behave", es: "comportarse", ej: "Behave well."},
    {en: "believe", es: "creer", ej: "I believe you."},
    {en: "belong", es: "pertenecer", ej: "This belongs to me."},
    {en: "beyond", es: "más allá", ej: "Beyond our budget."},
    {en: "bill", es: "factura", ej: "Pay the bill."},
    {en: "blame", es: "culpar", ej: "Don't blame me."},
    {en: "boring", es: "aburrido", ej: "The film was boring."},
    {en: "boss", es: "jefe", ej: "My boss is fair."},
    {en: "bother", es: "molestar", ej: "Don't bother her."},
    {en: "brand", es: "marca", ej: "A famous brand."},
    {en: "break", es: "romper / descanso", ej: "Take a break."},
    {en: "bring", es: "traer", ej: "Bring it here."},
    {en: "build", es: "construir", ej: "Build a team."},
    {en: "busy", es: "ocupado", ej: "I'm too busy."},
    {en: "buy", es: "comprar", ej: "I'll buy it."},
    {en: "cancel", es: "cancelar", ej: "Cancel the order."},
    {en: "capacity", es: "capacidad", ej: "Full capacity reached."},
    {en: "care", es: "cuidar / importar", ej: "I care about you."},
    {en: "career", es: "carrera profesional", ej: "A long career."},
    {en: "carry", es: "llevar", ej: "Carry this bag."}
  ],
  3: [
    {en: "cause", es: "causa / causar", ej: "What caused the issue?"},
    {en: "celebrate", es: "celebrar", ej: "Let's celebrate!"},
    {en: "certain", es: "cierto / seguro", ej: "I'm certain about it."},
    {en: "change", es: "cambiar", ej: "Change is good."},
    {en: "charge", es: "cobrar / cargar", ej: "How much do you charge?"},
    {en: "cheap", es: "barato", ej: "This is cheap."},
    {en: "check", es: "verificar", ej: "Check the email."},
    {en: "choice", es: "elección", ej: "Make a choice."},
    {en: "choose", es: "elegir", ej: "Choose wisely."},
    {en: "client", es: "cliente", ej: "A new client."},
    {en: "close", es: "cerrar / cerca", ej: "Close the door."},
    {en: "collect", es: "recoger / coleccionar", ej: "Collect the data."},
    {en: "common", es: "común", ej: "A common mistake."},
    {en: "compare", es: "comparar", ej: "Compare prices."},
    {en: "complain", es: "quejarse", ej: "Don't complain."},
    {en: "complete", es: "completar", ej: "Complete the form."},
    {en: "complex", es: "complejo", ej: "A complex issue."},
    {en: "conduct", es: "llevar a cabo", ej: "Conduct a study."},
    {en: "connect", es: "conectar", ej: "Connect the cable."},
    {en: "contact", es: "contactar", ej: "Contact support."},
    {en: "continue", es: "continuar", ej: "Continue working."},
    {en: "contract", es: "contrato", ej: "Sign the contract."},
    {en: "control", es: "controlar", ej: "Take control."},
    {en: "convince", es: "convencer", ej: "Convince the boss."},
    {en: "cost", es: "costar / coste", ej: "It costs 50 euros."},
    {en: "count", es: "contar", ej: "Count the votes."},
    {en: "cover", es: "cubrir", ej: "Cover the basics."},
    {en: "create", es: "crear", ej: "Create a plan."},
    {en: "current", es: "actual", ej: "The current state."},
    {en: "customer", es: "cliente", ej: "Happy customer."},
    {en: "damage", es: "daño / dañar", ej: "The storm caused damage."},
    {en: "deal", es: "trato / acuerdo", ej: "It's a deal."},
    {en: "decide", es: "decidir", ej: "Decide now."},
    {en: "decision", es: "decisión", ej: "Tough decision."},
    {en: "deep", es: "profundo", ej: "A deep lake."},
    {en: "delay", es: "retraso", ej: "There's a delay."},
    {en: "demand", es: "demandar / demanda", ej: "High demand."},
    {en: "depend", es: "depender", ej: "It depends."},
    {en: "describe", es: "describir", ej: "Describe yourself."},
    {en: "design", es: "diseñar", ej: "Nice design."},
    {en: "develop", es: "desarrollar", ej: "Develop a product."},
    {en: "die", es: "morir", ej: "He died last year."},
    {en: "difference", es: "diferencia", ej: "Big difference."},
    {en: "discuss", es: "discutir / hablar", ej: "Let's discuss it."},
    {en: "do", es: "hacer", ej: "Do your best."},
    {en: "doubt", es: "duda", ej: "Without a doubt."},
    {en: "draw", es: "dibujar", ej: "Draw a picture."},
    {en: "drop", es: "soltar / caer", ej: "Don't drop it."},
    {en: "early", es: "temprano", ej: "I woke up early."},
    {en: "earn", es: "ganar (dinero)", ej: "I earn a salary."}
  ],
  4: [
    {en: "edge", es: "borde", ej: "Cutting edge tech."},
    {en: "effect", es: "efecto", ej: "Side effect."},
    {en: "effort", es: "esfuerzo", ej: "Make an effort."},
    {en: "either", es: "cualquiera / tampoco", ej: "Either option works."},
    {en: "else", es: "otro / más", ej: "Anything else?"},
    {en: "employ", es: "emplear", ej: "We employ 50 people."},
    {en: "empty", es: "vacío", ej: "The box is empty."},
    {en: "encourage", es: "animar", ej: "I encourage you."},
    {en: "engage", es: "comprometerse", ej: "Engage the audience."},
    {en: "enjoy", es: "disfrutar", ej: "Enjoy your meal."},
    {en: "ensure", es: "asegurar", ej: "Ensure quality."},
    {en: "enter", es: "entrar", ej: "Enter the room."},
    {en: "entire", es: "entero", ej: "The entire team."},
    {en: "equal", es: "igual", ej: "Equal rights."},
    {en: "escape", es: "escapar", ej: "Escape the city."},
    {en: "even", es: "incluso / par", ej: "Even better."},
    {en: "event", es: "evento", ej: "A big event."},
    {en: "evidence", es: "prueba", ej: "Strong evidence."},
    {en: "exchange", es: "intercambio", ej: "Exchange rate."},
    {en: "exist", es: "existir", ej: "Does it exist?"},
    {en: "experience", es: "experiencia", ej: "Years of experience."},
    {en: "explain", es: "explicar", ej: "Explain it again."},
    {en: "express", es: "expresar", ej: "Express your view."},
    {en: "extra", es: "extra", ej: "Need extra help."},
    {en: "face", es: "cara / enfrentar", ej: "Face the truth."},
    {en: "factor", es: "factor", ej: "Key factor."},
    {en: "fair", es: "justo", ej: "Fair deal."},
    {en: "fall", es: "caer / caída", ej: "Don't fall."},
    {en: "fast", es: "rápido", ej: "Move fast."},
    {en: "fear", es: "miedo", ej: "No fear."},
    {en: "feel", es: "sentir", ej: "I feel good."},
    {en: "few", es: "pocos", ej: "A few minutes."},
    {en: "field", es: "campo", ej: "Field of work."},
    {en: "fill", es: "llenar", ej: "Fill the form."},
    {en: "finally", es: "finalmente", ej: "Finally home."},
    {en: "find", es: "encontrar", ej: "Find a solution."},
    {en: "fine", es: "bien / multa", ej: "I'm fine."},
    {en: "finish", es: "terminar", ej: "Finish the report."},
    {en: "fire", es: "fuego / despedir", ej: "Fire the employee."},
    {en: "fit", es: "encajar / en forma", ej: "It fits well."},
    {en: "fix", es: "arreglar", ej: "Fix the bug."},
    {en: "flat", es: "piso / plano", ej: "I rent a flat."},
    {en: "float", es: "flotar", ej: "It floats."},
    {en: "fly", es: "volar", ej: "Birds fly."},
    {en: "focus", es: "enfocar", ej: "Focus on goals."},
    {en: "follow", es: "seguir", ej: "Follow me."},
    {en: "force", es: "forzar / fuerza", ej: "Use force."},
    {en: "forget", es: "olvidar", ej: "Don't forget."},
    {en: "form", es: "forma / formar", ej: "Fill the form."},
    {en: "forward", es: "adelante / reenviar", ej: "Move forward."}
  ],
  5: [
    {en: "free", es: "libre / gratis", ej: "Free coffee."},
    {en: "fresh", es: "fresco", ej: "Fresh bread."},
    {en: "friend", es: "amigo", ej: "Best friend."},
    {en: "front", es: "frente", ej: "In front of."},
    {en: "full", es: "lleno", ej: "Full tank."},
    {en: "fun", es: "diversión", ej: "Have fun."},
    {en: "function", es: "función", ej: "It functions well."},
    {en: "fund", es: "fondo / financiar", ej: "Hedge fund."},
    {en: "further", es: "más lejos / adicional", ej: "Further info."},
    {en: "future", es: "futuro", ej: "Bright future."},
    {en: "gain", es: "ganar / ganancia", ej: "Gain experience."},
    {en: "game", es: "juego", ej: "Play a game."},
    {en: "gather", es: "reunir", ej: "Gather the team."},
    {en: "general", es: "general", ej: "General manager."},
    {en: "generate", es: "generar", ej: "Generate leads."},
    {en: "gentle", es: "suave / amable", ej: "Be gentle."},
    {en: "get", es: "obtener / conseguir", ej: "Get the keys."},
    {en: "give", es: "dar", ej: "Give it to me."},
    {en: "global", es: "global", ej: "Global market."},
    {en: "go", es: "ir", ej: "Let's go."},
    {en: "good", es: "bueno", ej: "Good job."},
    {en: "great", es: "genial", ej: "Great idea."},
    {en: "ground", es: "suelo / terreno", ej: "Solid ground."},
    {en: "group", es: "grupo", ej: "Work group."},
    {en: "grow", es: "crecer", ej: "Grow the business."},
    {en: "guess", es: "adivinar", ej: "Guess what."},
    {en: "guest", es: "invitado", ej: "VIP guest."},
    {en: "guide", es: "guiar / guía", ej: "Tour guide."},
    {en: "habit", es: "hábito", ej: "Good habit."},
    {en: "half", es: "mitad", ej: "Half done."},
    {en: "hand", es: "mano", ej: "Give me a hand."},
    {en: "handle", es: "manejar", ej: "Handle it."},
    {en: "happen", es: "suceder", ej: "It happens."},
    {en: "happy", es: "feliz", ej: "Happy birthday."},
    {en: "hard", es: "duro / difícil", ej: "Work hard."},
    {en: "harm", es: "daño", ej: "No harm done."},
    {en: "have", es: "tener", ej: "Have fun."},
    {en: "head", es: "cabeza / dirigir", ej: "Head of sales."},
    {en: "health", es: "salud", ej: "Good health."},
    {en: "hear", es: "oír", ej: "I hear you."},
    {en: "heart", es: "corazón", ej: "Heart attack."},
    {en: "heavy", es: "pesado", ej: "Heavy box."},
    {en: "help", es: "ayudar", ej: "Help me."},
    {en: "hide", es: "esconder", ej: "Hide the gift."},
    {en: "high", es: "alto", ej: "High quality."},
    {en: "hold", es: "sostener", ej: "Hold on."},
    {en: "hope", es: "esperar / esperanza", ej: "I hope so."},
    {en: "however", es: "sin embargo", ej: "However, wait."},
    {en: "huge", es: "enorme", ej: "Huge success."},
    {en: "human", es: "humano", ej: "Human nature."}
  ],
  6: [
    {en: "idea", es: "idea", ej: "Good idea."},
    {en: "identify", es: "identificar", ej: "Identify the problem."},
    {en: "image", es: "imagen", ej: "Brand image."},
    {en: "imagine", es: "imaginar", ej: "Imagine that."},
    {en: "impact", es: "impacto", ej: "Big impact."},
    {en: "important", es: "importante", ej: "Very important."},
    {en: "include", es: "incluir", ej: "Include everyone."},
    {en: "indeed", es: "ciertamente", ej: "Indeed, you're right."},
    {en: "industry", es: "industria", ej: "Tech industry."},
    {en: "influence", es: "influencia", ej: "Big influence."},
    {en: "inform", es: "informar", ej: "Inform the team."},
    {en: "initial", es: "inicial", ej: "Initial phase."},
    {en: "inside", es: "dentro", ej: "Inside the box."},
    {en: "instead", es: "en lugar de", ej: "Instead of coffee."},
    {en: "intend", es: "tener intención", ej: "I intend to go."},
    {en: "interest", es: "interés", ej: "No interest."},
    {en: "internal", es: "interno", ej: "Internal meeting."},
    {en: "introduce", es: "introducir / presentar", ej: "Introduce yourself."},
    {en: "invest", es: "invertir", ej: "Invest wisely."},
    {en: "involve", es: "involucrar", ej: "Involve the team."},
    {en: "join", es: "unirse", ej: "Join us."},
    {en: "judge", es: "juzgar", ej: "Don't judge."},
    {en: "keep", es: "mantener / guardar", ej: "Keep going."},
    {en: "kind", es: "tipo / amable", ej: "Kind regards."},
    {en: "know", es: "saber / conocer", ej: "I know that."},
    {en: "knowledge", es: "conocimiento", ej: "Useful knowledge."},
    {en: "land", es: "tierra / aterrizar", ej: "Land the plane."},
    {en: "large", es: "grande", ej: "Large company."},
    {en: "last", es: "último / durar", ej: "Last chance."},
    {en: "late", es: "tarde", ej: "Don't be late."},
    {en: "lay", es: "poner / yacer", ej: "Lay it down."},
    {en: "lead", es: "liderar", ej: "Lead the team."},
    {en: "learn", es: "aprender", ej: "Learn fast."},
    {en: "least", es: "menos", ej: "At least try."},
    {en: "leave", es: "dejar / irse", ej: "Leave now."},
    {en: "less", es: "menos", ej: "Less is more."},
    {en: "let", es: "dejar / permitir", ej: "Let me see."},
    {en: "level", es: "nivel", ej: "High level."},
    {en: "lie", es: "mentir / yacer", ej: "Don't lie."},
    {en: "life", es: "vida", ej: "Life is good."},
    {en: "light", es: "luz / ligero", ej: "Turn on the light."},
    {en: "like", es: "gustar / como", ej: "I like it."},
    {en: "likely", es: "probable", ej: "Most likely yes."},
    {en: "limit", es: "límite", ej: "No limit."},
    {en: "link", es: "enlace", ej: "Click the link."},
    {en: "list", es: "lista", ej: "Make a list."},
    {en: "listen", es: "escuchar", ej: "Listen carefully."},
    {en: "little", es: "pequeño / poco", ej: "A little time."},
    {en: "live", es: "vivir / vivo", ej: "Live stream."},
    {en: "load", es: "cargar", ej: "Load the truck."}
  ],
  7: [
    {en: "local", es: "local", ej: "Local store."},
    {en: "long", es: "largo", ej: "Long day."},
    {en: "look", es: "mirar / parecer", ej: "Look here."},
    {en: "lose", es: "perder", ej: "Don't lose hope."},
    {en: "loud", es: "ruidoso", ej: "Too loud."},
    {en: "love", es: "amor / amar", ej: "I love it."},
    {en: "low", es: "bajo", ej: "Low price."},
    {en: "lucky", es: "afortunado", ej: "Lucky me."},
    {en: "main", es: "principal", ej: "Main idea."},
    {en: "maintain", es: "mantener", ej: "Maintain quality."},
    {en: "major", es: "principal / mayor", ej: "Major change."},
    {en: "make", es: "hacer", ej: "Make sense."},
    {en: "manner", es: "manera", ej: "Polite manner."},
    {en: "many", es: "muchos", ej: "Many people."},
    {en: "mark", es: "marca / marcar", ej: "Mark the date."},
    {en: "market", es: "mercado", ej: "Free market."},
    {en: "match", es: "coincidir / partido", ej: "Match made."},
    {en: "matter", es: "importar / asunto", ej: "It matters."},
    {en: "may", es: "poder (permiso)", ej: "May I help?"},
    {en: "mean", es: "significar / malo", ej: "What do you mean?"},
    {en: "measure", es: "medir", ej: "Measure twice."},
    {en: "meet", es: "encontrarse", ej: "Nice to meet you."},
    {en: "meeting", es: "reunión", ej: "Daily meeting."},
    {en: "member", es: "miembro", ej: "Team member."},
    {en: "mention", es: "mencionar", ej: "Don't mention it."},
    {en: "message", es: "mensaje", ej: "Short message."},
    {en: "method", es: "método", ej: "New method."},
    {en: "middle", es: "medio", ej: "Middle of the day."},
    {en: "might", es: "podría", ej: "I might come."},
    {en: "mind", es: "mente", ej: "Never mind."},
    {en: "minute", es: "minuto", ej: "One minute."},
    {en: "miss", es: "perder / extrañar", ej: "I miss you."},
    {en: "mistake", es: "error", ej: "Big mistake."},
    {en: "model", es: "modelo", ej: "Business model."},
    {en: "moment", es: "momento", ej: "Right moment."},
    {en: "money", es: "dinero", ej: "More money."},
    {en: "month", es: "mes", ej: "Last month."},
    {en: "more", es: "más", ej: "Want more?"},
    {en: "most", es: "la mayoría", ej: "Most people."},
    {en: "move", es: "mover", ej: "Move forward."},
    {en: "much", es: "mucho", ej: "Too much."},
    {en: "must", es: "deber", ej: "You must go."},
    {en: "name", es: "nombre", ej: "My name is."},
    {en: "narrow", es: "estrecho", ej: "Narrow street."},
    {en: "near", es: "cerca", ej: "Near the office."},
    {en: "necessary", es: "necesario", ej: "Not necessary."},
    {en: "need", es: "necesitar", ej: "I need help."},
    {en: "neither", es: "ninguno", ej: "Neither one."},
    {en: "never", es: "nunca", ej: "Never give up."},
    {en: "new", es: "nuevo", ej: "New product."}
  ],
  8: [
    {en: "next", es: "siguiente", ej: "Next week."},
    {en: "nice", es: "agradable", ej: "Nice to meet."},
    {en: "no longer", es: "ya no", ej: "No longer here."},
    {en: "nobody", es: "nadie", ej: "Nobody knows."},
    {en: "noise", es: "ruido", ej: "Loud noise."},
    {en: "none", es: "ninguno", ej: "None of them."},
    {en: "normal", es: "normal", ej: "Normal day."},
    {en: "note", es: "nota", ej: "Take note."},
    {en: "nothing", es: "nada", ej: "Nothing here."},
    {en: "notice", es: "notar / aviso", ej: "I noticed it."},
    {en: "now", es: "ahora", ej: "Right now."},
    {en: "number", es: "número", ej: "Phone number."},
    {en: "obvious", es: "obvio", ej: "Obvious answer."},
    {en: "occur", es: "ocurrir", ej: "It occurred to me."},
    {en: "of course", es: "por supuesto", ej: "Of course!"},
    {en: "offer", es: "oferta / ofrecer", ej: "Good offer."},
    {en: "office", es: "oficina", ej: "At the office."},
    {en: "often", es: "a menudo", ej: "I often work late."},
    {en: "old", es: "viejo", ej: "Old friend."},
    {en: "once", es: "una vez", ej: "Once upon a time."},
    {en: "only", es: "solo", ej: "Only one left."},
    {en: "open", es: "abrir / abierto", ej: "Open the door."},
    {en: "operate", es: "operar", ej: "Operate the machine."},
    {en: "opinion", es: "opinión", ej: "My opinion is."},
    {en: "opportunity", es: "oportunidad", ej: "Big opportunity."},
    {en: "option", es: "opción", ej: "Best option."},
    {en: "order", es: "pedido / orden", ej: "Place an order."},
    {en: "ordinary", es: "ordinario", ej: "Ordinary day."},
    {en: "organize", es: "organizar", ej: "Organize the files."},
    {en: "other", es: "otro", ej: "The other one."},
    {en: "outside", es: "fuera", ej: "Outside the box."},
    {en: "over", es: "sobre / terminado", ej: "It's over."},
    {en: "owner", es: "dueño", ej: "The owner."},
    {en: "page", es: "página", ej: "Next page."},
    {en: "pain", es: "dolor", ej: "Back pain."},
    {en: "paper", es: "papel", ej: "Sheet of paper."},
    {en: "part", es: "parte", ej: "A big part."},
    {en: "particular", es: "particular", ej: "In particular."},
    {en: "partner", es: "socio / pareja", ej: "Business partner."},
    {en: "party", es: "fiesta / partido", ej: "Birthday party."},
    {en: "pass", es: "pasar", ej: "Pass the salt."},
    {en: "past", es: "pasado", ej: "In the past."},
    {en: "path", es: "camino", ej: "Career path."},
    {en: "patient", es: "paciente", ej: "Be patient."},
    {en: "pay", es: "pagar", ej: "Pay the bill."},
    {en: "peace", es: "paz", ej: "World peace."},
    {en: "people", es: "gente", ej: "Many people."},
    {en: "percent", es: "por ciento", ej: "Ten percent."},
    {en: "perhaps", es: "quizás", ej: "Perhaps later."},
    {en: "period", es: "período", ej: "Trial period."}
  ],
  9: [
    {en: "person", es: "persona", ej: "Nice person."},
    {en: "phone", es: "teléfono", ej: "Call the phone."},
    {en: "pick", es: "elegir / recoger", ej: "Pick one."},
    {en: "picture", es: "imagen", ej: "Take a picture."},
    {en: "piece", es: "pieza", ej: "A piece of cake."},
    {en: "place", es: "lugar", ej: "Nice place."},
    {en: "plan", es: "plan", ej: "Make a plan."},
    {en: "play", es: "jugar / tocar", ej: "Play music."},
    {en: "please", es: "por favor / agradar", ej: "Please help."},
    {en: "point", es: "punto", ej: "Good point."},
    {en: "policy", es: "política", ej: "Company policy."},
    {en: "poor", es: "pobre", ej: "Poor quality."},
    {en: "popular", es: "popular", ej: "Popular brand."},
    {en: "position", es: "posición", ej: "Strong position."},
    {en: "possible", es: "posible", ej: "If possible."},
    {en: "post", es: "publicar / correo", ej: "Post a comment."},
    {en: "power", es: "poder", ej: "Power up."},
    {en: "practice", es: "práctica", ej: "Practice makes perfect."},
    {en: "prefer", es: "preferir", ej: "I prefer tea."},
    {en: "prepare", es: "preparar", ej: "Prepare a report."},
    {en: "present", es: "presente / presentar", ej: "Present the data."},
    {en: "press", es: "presionar / prensa", ej: "Press the button."},
    {en: "pretty", es: "bonito / bastante", ej: "Pretty good."},
    {en: "prevent", es: "prevenir", ej: "Prevent issues."},
    {en: "previous", es: "previo", ej: "Previous job."},
    {en: "price", es: "precio", ej: "High price."},
    {en: "private", es: "privado", ej: "Private meeting."},
    {en: "probably", es: "probablemente", ej: "Probably yes."},
    {en: "problem", es: "problema", ej: "Big problem."},
    {en: "process", es: "proceso", ej: "Slow process."},
    {en: "produce", es: "producir", ej: "Produce more."},
    {en: "product", es: "producto", ej: "New product."},
    {en: "professional", es: "profesional", ej: "Professional team."},
    {en: "profit", es: "beneficio (económico)", ej: "Net profit."},
    {en: "program", es: "programa", ej: "TV program."},
    {en: "project", es: "proyecto", ej: "New project."},
    {en: "promise", es: "promesa / prometer", ej: "I promise."},
    {en: "promote", es: "promover", ej: "Promote the product."},
    {en: "proper", es: "apropiado", ej: "Proper way."},
    {en: "property", es: "propiedad", ej: "Private property."},
    {en: "propose", es: "proponer", ej: "Propose a plan."},
    {en: "protect", es: "proteger", ej: "Protect the data."},
    {en: "prove", es: "probar / demostrar", ej: "Prove it."},
    {en: "provider", es: "proveedor", ej: "Service provider."},
    {en: "public", es: "público", ej: "Public space."},
    {en: "publish", es: "publicar", ej: "Publish a book."},
    {en: "pull", es: "tirar de", ej: "Pull the rope."},
    {en: "purchase", es: "compra", ej: "Online purchase."},
    {en: "purpose", es: "propósito", ej: "On purpose."},
    {en: "push", es: "empujar", ej: "Push the door."}
  ],
  10: [
    {en: "put", es: "poner", ej: "Put it down."},
    {en: "quality", es: "calidad", ej: "High quality."},
    {en: "question", es: "pregunta", ej: "Ask a question."},
    {en: "quick", es: "rápido", ej: "Quick reply."},
    {en: "quiet", es: "silencioso", ej: "Quiet please."},
    {en: "quite", es: "bastante", ej: "Quite good."},
    {en: "range", es: "rango", ej: "Wide range."},
    {en: "rate", es: "tasa / valorar", ej: "Interest rate."},
    {en: "reach", es: "alcanzar", ej: "Reach me by email."},
    {en: "react", es: "reaccionar", ej: "React quickly."},
    {en: "read", es: "leer", ej: "Read the book."},
    {en: "ready", es: "listo", ej: "Are you ready?"},
    {en: "real", es: "real", ej: "Real story."},
    {en: "realize", es: "darse cuenta", ej: "I realized it."},
    {en: "reason", es: "razón", ej: "Good reason."},
    {en: "receive", es: "recibir", ej: "Receive the package."},
    {en: "recent", es: "reciente", ej: "Recent news."},
    {en: "recognize", es: "reconocer", ej: "Recognize the voice."},
    {en: "record", es: "registro / grabar", ej: "Record the call."},
    {en: "refer", es: "referirse", ej: "Refer to the manual."},
    {en: "reflect", es: "reflejar", ej: "Reflect on it."},
    {en: "refuse", es: "rechazar", ej: "I refuse."},
    {en: "regard", es: "considerar", ej: "Best regards."},
    {en: "region", es: "región", ej: "Local region."},
    {en: "regular", es: "regular", ej: "Regular customer."},
    {en: "relate", es: "relacionar", ej: "Relate to that."},
    {en: "release", es: "lanzar / liberar", ej: "Release the product."},
    {en: "remain", es: "permanecer", ej: "Remain calm."},
    {en: "remember", es: "recordar", ej: "Remember me?"},
    {en: "remove", es: "quitar", ej: "Remove the file."},
    {en: "repeat", es: "repetir", ej: "Repeat please."},
    {en: "replace", es: "reemplazar", ej: "Replace the part."},
    {en: "reply", es: "responder", ej: "Quick reply."},
    {en: "report", es: "informe", ej: "Annual report."},
    {en: "represent", es: "representar", ej: "Represent the firm."},
    {en: "request", es: "solicitud", ej: "Send a request."},
    {en: "respect", es: "respetar", ej: "Respect others."},
    {en: "respond", es: "responder", ej: "Respond fast."},
    {en: "rest", es: "descansar / resto", ej: "Take a rest."},
    {en: "result", es: "resultado", ej: "Final result."},
    {en: "return", es: "volver / devolver", ej: "Return home."},
    {en: "reveal", es: "revelar", ej: "Reveal the plan."},
    {en: "review", es: "revisar", ej: "Review the code."},
    {en: "rich", es: "rico", ej: "Rich man."},
    {en: "right", es: "correcto / derecho", ej: "You're right."},
    {en: "rise", es: "subir / aumentar", ej: "Prices rise."},
    {en: "risk", es: "riesgo", ej: "Take a risk."},
    {en: "road", es: "carretera", ej: "Long road."},
    {en: "role", es: "rol", ej: "Key role."},
    {en: "rough", es: "duro / áspero", ej: "Rough day."}
  ]
};
